In [ ]:
#| hide
from emdtool.core import *

# emdtool

> tool to assist electric machine design and analysis

This file will become your README and also the index of your documentation.

## Install

```sh
pip install emdtool
```

## How to use

Fill me in please! Don't forget code examples:

In [ ]:
#| hide
import sys
#import numpy as np
#adding additional path to system for searching libraries
sys.path.insert(0,'/home/vnd/MotorDesigner/emdtool')

In [ ]:
# import the tool
from emdtool import dq

In [ ]:
# multiply a column vector of abc values to get corresponding dq0 values
angle = 0
abc = [[1], [-0.5], [-0.5]]
dq0 = dq.transform(angle, abc)

tranformation matrix (shape:(3, 3)): 
[[ 0.66666667 -0.33333333 -0.33333333]
 [ 0.         -0.57735027  0.57735027]
 [ 0.33333333  0.33333333  0.33333333]]

abc matrix (shape:(3, 1)): 
[[ 1. ]
 [-0.5]
 [-0.5]]

tranformed matrix: 
 [[1.]
 [0.]
 [0.]]
